# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uinew3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 805)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(490, 10, 297, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalLayout_2.addWidget(self.horizontalSlider_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Class"))
        self.comboBox.setItemText(0, _translate("MainWindow", "airplane"))
        self.comboBox.setItemText(1, _translate("MainWindow", "bathtub"))
        self.comboBox.setItemText(2, _translate("MainWindow", "bed"))
        self.comboBox.setItemText(3, _translate("MainWindow", "bench"))
        self.comboBox.setItemText(4, _translate("MainWindow", "bookshelf"))
        self.comboBox.setItemText(5, _translate("MainWindow", "bottle"))
        self.comboBox.setItemText(6, _translate("MainWindow", "bowl"))
        self.comboBox.setItemText(7, _translate("MainWindow", "car"))
        self.comboBox.setItemText(8, _translate("MainWindow", "chair"))
        self.comboBox.setItemText(9, _translate("MainWindow", "cone"))
        self.comboBox.setItemText(10, _translate("MainWindow", "cup"))
        self.comboBox.setItemText(11, _translate("MainWindow", "curtain"))
        self.comboBox.setItemText(12, _translate("MainWindow", "desk"))
        self.comboBox.setItemText(13, _translate("MainWindow", "door"))
        self.comboBox.setItemText(14, _translate("MainWindow", "dresser"))
        self.comboBox.setItemText(15, _translate("MainWindow", "flower_pot"))
        self.comboBox.setItemText(16, _translate("MainWindow", "glass_box"))
        self.comboBox.setItemText(17, _translate("MainWindow", "guitar"))
        self.comboBox.setItemText(18, _translate("MainWindow", "keyboard"))
        self.comboBox.setItemText(19, _translate("MainWindow", "lamp"))
        self.comboBox.setItemText(20, _translate("MainWindow", "laptop"))
        self.comboBox.setItemText(21, _translate("MainWindow", "mantel"))
        self.comboBox.setItemText(22, _translate("MainWindow", "monitor"))
        self.comboBox.setItemText(23, _translate("MainWindow", "night_stand"))
        self.comboBox.setItemText(24, _translate("MainWindow", "person"))
        self.comboBox.setItemText(25, _translate("MainWindow", "piano"))
        self.comboBox.setItemText(26, _translate("MainWindow", "plant"))
        self.comboBox.setItemText(27, _translate("MainWindow", "radio"))
        self.comboBox.setItemText(28, _translate("MainWindow", "range_hood"))
        self.comboBox.setItemText(29, _translate("MainWindow", "sink"))
        self.comboBox.setItemText(30, _translate("MainWindow", "sofa"))
        self.comboBox.setItemText(31, _translate("MainWindow", "stairs"))
        self.comboBox.setItemText(32, _translate("MainWindow", "stool"))
        self.comboBox.setItemText(33, _translate("MainWindow", "table"))
        self.comboBox.setItemText(34, _translate("MainWindow", "tent"))
        self.comboBox.setItemText(35, _translate("MainWindow", "toilt"))
        self.comboBox.setItemText(36, _translate("MainWindow", "tv_stand"))
        self.comboBox.setItemText(37, _translate("MainWindow", "vase"))
        self.comboBox.setItemText(38, _translate("MainWindow", "wardrobe"))
        self.comboBox.setItemText(39, _translate("MainWindow", "xbox"))
        self.label_2.setText(_translate("MainWindow", "Index"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "0001"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "0002"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "0003"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "0004"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "0005"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "0006"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "0007"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "0008"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "0009"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "0010"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "0011"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "0012"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "0013"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "0014"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "0015"))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "0016"))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "0017"))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "0018"))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "0019"))
        self.comboBox_2.setItemText(19, _translate("MainWindow", "0020"))
        self.comboBox_2.setItemText(20, _translate("MainWindow", "0021"))
        self.comboBox_2.setItemText(21, _translate("MainWindow", "0022"))
        self.comboBox_2.setItemText(22, _translate("MainWindow", "0023"))
        self.comboBox_2.setItemText(23, _translate("MainWindow", "0024"))
        self.comboBox_2.setItemText(24, _translate("MainWindow", "0025"))
        self.comboBox_2.setItemText(25, _translate("MainWindow", "0026"))
        self.comboBox_2.setItemText(26, _translate("MainWindow", "0027"))
        self.comboBox_2.setItemText(27, _translate("MainWindow", "0028"))
        self.comboBox_2.setItemText(28, _translate("MainWindow", "0029"))
        self.comboBox_2.setItemText(29, _translate("MainWindow", "0030"))
        self.comboBox_2.setItemText(30, _translate("MainWindow", "0031"))
        self.comboBox_2.setItemText(31, _translate("MainWindow", "0032"))
        self.comboBox_2.setItemText(32, _translate("MainWindow", "0033"))
        self.comboBox_2.setItemText(33, _translate("MainWindow", "0034"))
        self.comboBox_2.setItemText(34, _translate("MainWindow", "0035"))
        self.comboBox_2.setItemText(35, _translate("MainWindow", "0036"))
        self.comboBox_2.setItemText(36, _translate("MainWindow", "0037"))
        self.comboBox_2.setItemText(37, _translate("MainWindow", "0038"))
        self.comboBox_2.setItemText(38, _translate("MainWindow", "0039"))
        self.comboBox_2.setItemText(39, _translate("MainWindow", "0040"))
        self.comboBox_2.setItemText(40, _translate("MainWindow", "0041"))
        self.comboBox_2.setItemText(41, _translate("MainWindow", "0042"))
        self.comboBox_2.setItemText(42, _translate("MainWindow", "0043"))
        self.comboBox_2.setItemText(43, _translate("MainWindow", "0044"))
        self.comboBox_2.setItemText(44, _translate("MainWindow", "0045"))
        self.comboBox_2.setItemText(45, _translate("MainWindow", "0046"))
        self.comboBox_2.setItemText(46, _translate("MainWindow", "0047"))
        self.comboBox_2.setItemText(47, _translate("MainWindow", "0048"))
        self.comboBox_2.setItemText(48, _translate("MainWindow", "0049"))
        self.comboBox_2.setItemText(49, _translate("MainWindow", "0050"))
        self.comboBox_2.setItemText(50, _translate("MainWindow", "0051"))
        self.comboBox_2.setItemText(51, _translate("MainWindow", "0052"))
        self.comboBox_2.setItemText(52, _translate("MainWindow", "0053"))
        self.comboBox_2.setItemText(53, _translate("MainWindow", "0054"))
        self.comboBox_2.setItemText(54, _translate("MainWindow", "0055"))
        self.comboBox_2.setItemText(55, _translate("MainWindow", "0056"))
        self.comboBox_2.setItemText(56, _translate("MainWindow", "0057"))
        self.comboBox_2.setItemText(57, _translate("MainWindow", "0058"))
        self.comboBox_2.setItemText(58, _translate("MainWindow", "0059"))
        self.comboBox_2.setItemText(59, _translate("MainWindow", "0060"))
        self.comboBox_2.setItemText(60, _translate("MainWindow", "0061"))
        self.comboBox_2.setItemText(61, _translate("MainWindow", "0062"))
        self.comboBox_2.setItemText(62, _translate("MainWindow", "0063"))
        self.comboBox_2.setItemText(63, _translate("MainWindow", "0064"))
        self.comboBox_2.setItemText(64, _translate("MainWindow", "0065"))
        self.comboBox_2.setItemText(65, _translate("MainWindow", "0066"))
        self.comboBox_2.setItemText(66, _translate("MainWindow", "0067"))
        self.comboBox_2.setItemText(67, _translate("MainWindow", "0068"))
        self.comboBox_2.setItemText(68, _translate("MainWindow", "0069"))
        self.comboBox_2.setItemText(69, _translate("MainWindow", "0070"))
        self.comboBox_2.setItemText(70, _translate("MainWindow", "0071"))
        self.comboBox_2.setItemText(71, _translate("MainWindow", "0072"))
        self.comboBox_2.setItemText(72, _translate("MainWindow", "0073"))
        self.comboBox_2.setItemText(73, _translate("MainWindow", "0074"))
        self.comboBox_2.setItemText(74, _translate("MainWindow", "0075"))
        self.comboBox_2.setItemText(75, _translate("MainWindow", "0076"))
        self.comboBox_2.setItemText(76, _translate("MainWindow", "0077"))
        self.comboBox_2.setItemText(77, _translate("MainWindow", "0078"))
        self.comboBox_2.setItemText(78, _translate("MainWindow", "0079"))
        self.comboBox_2.setItemText(79, _translate("MainWindow", "0080"))
        self.comboBox_2.setItemText(80, _translate("MainWindow", "0081"))
        self.comboBox_2.setItemText(81, _translate("MainWindow", "0082"))
        self.comboBox_2.setItemText(82, _translate("MainWindow", "0083"))
        self.comboBox_2.setItemText(83, _translate("MainWindow", "0084"))
        self.comboBox_2.setItemText(84, _translate("MainWindow", "0085"))
        self.comboBox_2.setItemText(85, _translate("MainWindow", "0086"))
        self.comboBox_2.setItemText(86, _translate("MainWindow", "0087"))
        self.comboBox_2.setItemText(87, _translate("MainWindow", "0088"))
        self.comboBox_2.setItemText(88, _translate("MainWindow", "0089"))
        self.comboBox_2.setItemText(89, _translate("MainWindow", "0090"))
        self.comboBox_2.setItemText(90, _translate("MainWindow", "0091"))
        self.comboBox_2.setItemText(91, _translate("MainWindow", "0092"))
        self.comboBox_2.setItemText(92, _translate("MainWindow", "0093"))
        self.comboBox_2.setItemText(93, _translate("MainWindow", "0094"))
        self.comboBox_2.setItemText(94, _translate("MainWindow", "0095"))
        self.comboBox_2.setItemText(95, _translate("MainWindow", "0096"))
        self.comboBox_2.setItemText(96, _translate("MainWindow", "0097"))
        self.comboBox_2.setItemText(97, _translate("MainWindow", "0098"))
        self.comboBox_2.setItemText(98, _translate("MainWindow", "0099"))
        self.comboBox_2.setItemText(99, _translate("MainWindow", "0100"))
        self.label_3.setText(_translate("MainWindow", "Points"))
        self.radioButton.setText(_translate("MainWindow", "All"))
        self.radioButton_2.setText(_translate("MainWindow", "Max"))
        self.pushButton_3.setText(_translate("MainWindow", "Load"))
        self.label_4.setText(_translate("MainWindow", "Size"))
        self.pushButton.setText(_translate("MainWindow", "Reduce"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "Enlarge"))
        self.label_6.setText(_translate("MainWindow", "Points Size"))
        self.label_5.setText(_translate("MainWindow", "Color"))
        self.pushButton_4.setText(_translate("MainWindow", "Save"))
        self.pushButton_5.setText(_translate("MainWindow", "Exit"))

